# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml


  tasks:
    - name: Delete web VM 
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        datacenter: "{{ vsphere_datacenter }}"
        cluster: "{{ vsphere_cluster }}"
        folder: "{{ vsphere_folder }}"
        name: "{{ vm_name[0].name }}_deployed_by_ansible"
        state: absent
        force: yes

      tags: webvm

    - name: Delete app VM
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        datacenter: "{{ vsphere_datacenter }}"
        cluster: "{{ vsphere_cluster }}"
        folder: "{{ vsphere_folder }}"
        name: "{{ vm_name[1].name }}_deployed_by_ansible"
        state: absent
        force: yes

    - name: Delete db VM
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        datacenter: "{{ vsphere_datacenter }}"
        cluster: "{{ vsphere_cluster }}"
        folder: "{{ vsphere_folder }}"
        name: "{{ vm_name[2].name }}_deployed_by_ansible"
        state: absent
        force: yes

